use super::connection::{
    AddRowValue, DatabaseConnection, SchemaColumnDefinition, SchemaMutationResult, SchemaOperation,
    SchemaOperationType,
};
use super::create_connection;
use serde_json::Value;
use std::env;
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

// Integration tests are intentionally ignored by default.
// Run them explicitly with `cargo test -- --ignored` after providing:
// - BLOATSQL_TEST_POSTGRES_HOST / PORT / USER / PASSWORD / DATABASE
// - BLOATSQL_TEST_MARIADB_HOST / PORT / USER / PASSWORD / DATABASE
// Optional: `*_SSL_MODE` (defaults to `disabled`).

#[derive(Clone, Copy)]
enum TestBackend {
    Postgres,
    MariaDb,
}

impl TestBackend {
    fn env_prefix(self) -> &'static str {
        match self {
            Self::Postgres => "BLOATSQL_TEST_POSTGRES",
            Self::MariaDb => "BLOATSQL_TEST_MARIADB",
        }
    }

    fn db_type(self) -> &'static str {
        match self {
            Self::Postgres => "postgresql",
            Self::MariaDb => "mariadb",
        }
    }

    fn table_prefix(self) -> &'static str {
        match self {
            Self::Postgres => "pg",
            Self::MariaDb => "mariadb",
        }
    }

    fn quote_identifier(self, identifier: &str) -> String {
        match self {
            Self::Postgres => format!("\"{}\"", identifier),
            Self::MariaDb => format!("`{}`", identifier),
        }
    }

    fn create_table_sql(self, table_name: &str) -> String {
        let quoted_table = self.quote_identifier(table_name);

        match self {
            Self::Postgres => format!(
                "CREATE TABLE {} (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL DEFAULT 'anonymous', notes TEXT NULL)",
                quoted_table
            ),
            Self::MariaDb => format!(
                "CREATE TABLE {} (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL DEFAULT 'anonymous', notes TEXT NULL)",
                quoted_table
            ),
        }
    }
}

struct TestDbConfig {
    backend: TestBackend,
    host: String,
    port: u16,
    username: String,
    password: String,
    database: String,
    ssl_mode: String,
}

impl TestDbConfig {
    fn from_env(backend: TestBackend) -> Self {
        let prefix = backend.env_prefix();

        Self {
            backend,
            host: required_env(prefix, "HOST"),
            port: parse_port(prefix),
            username: required_env(prefix, "USER"),
            password: required_env(prefix, "PASSWORD"),
            database: required_env(prefix, "DATABASE"),
            ssl_mode: env::var(format!("{}_SSL_MODE", prefix)).unwrap_or_else(|_| "disabled".to_string()),
        }
    }

    async fn connect(&self) -> Arc<dyn DatabaseConnection> {
        create_connection(
            self.backend.db_type(),
            &self.host,
            self.port,
            &self.username,
            &self.password,
            &self.database,
            &self.ssl_mode,
        )
        .await
        .unwrap_or_else(|error| {
            panic!(
                "Failed to connect to {} test database: {} ({:?})",
                self.backend.db_type(),
                error.message,
                error.code
            )
        })
    }
}

fn required_env(prefix: &str, suffix: &str) -> String {
    let key = format!("{}_{}", prefix, suffix);
    env::var(&key).unwrap_or_else(|_| panic!("Missing required env var: {}", key))
}

fn parse_port(prefix: &str) -> u16 {
    let key = format!("{}_PORT", prefix);
    env::var(&key)
        .unwrap_or_else(|_| panic!("Missing required env var: {}", key))
        .parse()
        .unwrap_or_else(|_| panic!("{} must be a valid u16 port", key))
}

fn unique_table_name(backend: TestBackend, scenario: &str) -> String {
    let millis = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system time should be after unix epoch")
        .as_millis();

    format!("bloatsql_it_{}_{}_{}", backend.table_prefix(), scenario, millis)
}

async fn drop_table_if_exists(
    connection: &Arc<dyn DatabaseConnection>,
    backend: TestBackend,
    table_name: &str,
) {
    let drop_sql = format!(
        "DROP TABLE IF EXISTS {}",
        backend.quote_identifier(table_name)
    );

    connection
        .execute_query(&drop_sql)
        .await
        .unwrap_or_else(|error| panic!("Failed to drop test table {}: {}", table_name, error.message));
}

async fn fetch_rows(
    connection: &Arc<dyn DatabaseConnection>,
    backend: TestBackend,
    table_name: &str,
    select_list: &str,
) -> Vec<Value> {
    let query = format!(
        "SELECT {} FROM {} ORDER BY id",
        select_list,
        backend.quote_identifier(table_name)
    );

    connection
        .execute_query(&query)
        .await
        .unwrap_or_else(|error| panic!("Failed to query {}: {}", table_name, error.message))
        .rows
}

fn json_field_as_string(row: &Value, field: &str) -> String {
    row.get(field)
        .unwrap_or_else(|| panic!("Missing field '{}' in row: {}", field, row))
        .as_str()
        .map(ToString::to_string)
        .unwrap_or_else(|| {
            row.get(field)
                .unwrap_or_else(|| panic!("Missing field '{}' in row: {}", field, row))
                .to_string()
        })
}

fn build_add_status_operation() -> SchemaOperation {
    SchemaOperation {
        operation_type: SchemaOperationType::AddColumn,
        column_name: "status".to_string(),
        new_column_name: None,
        new_definition: Some(SchemaColumnDefinition {
            name: "status".to_string(),
            data_type: "VARCHAR".to_string(),
            length: Some(32),
            is_nullable: false,
            is_primary_key: false,
            default_value: Some("active".to_string()),
        }),
    }
}

async fn assert_successful_mutation_flow(config: TestDbConfig) {
    let connection = config.connect().await;
    let table_name = unique_table_name(config.backend, "mutations");

    drop_table_if_exists(&connection, config.backend, &table_name).await;
    connection
        .execute_query(&config.backend.create_table_sql(&table_name))
        .await
        .unwrap_or_else(|error| panic!("Failed to create test table {}: {}", table_name, error.message));

    connection
        .add_row(
            &table_name,
            &[
                AddRowValue {
                    column_name: "id".to_string(),
                    value: None,
                    use_default: true,
                },
                AddRowValue {
                    column_name: "name".to_string(),
                    value: Some("Alice".to_string()),
                    use_default: false,
                },
                AddRowValue {
                    column_name: "notes".to_string(),
                    value: None,
                    use_default: false,
                },
            ],
        )
        .await
        .unwrap_or_else(|error| panic!("add_row explicit insert failed: {}", error.message));

    connection
        .add_row(&table_name, &[])
        .await
        .unwrap_or_else(|error| panic!("add_row default insert failed: {}", error.message));

    let rows = fetch_rows(&connection, config.backend, &table_name, "id, name, notes").await;
    assert_eq!(rows.len(), 2, "expected two rows after add_row");
    assert_eq!(rows[0]["name"], Value::String("Alice".to_string()));
    assert!(rows[0]["notes"].is_null(), "explicit NULL should be stored as null");
    assert_eq!(rows[1]["name"], Value::String("anonymous".to_string()));

    let first_id = json_field_as_string(&rows[0], "id");
    let second_id = json_field_as_string(&rows[1], "id");

    connection
        .update_cell(&table_name, "notes", Some("updated"), "id", &first_id)
        .await
        .unwrap_or_else(|error| panic!("update_cell failed: {}", error.message));

    let updated_rows = fetch_rows(&connection, config.backend, &table_name, "id, notes").await;
    let updated_first = updated_rows
        .iter()
        .find(|row| json_field_as_string(row, "id") == first_id)
        .expect("expected updated row to exist");
    assert_eq!(updated_first["notes"], Value::String("updated".to_string()));

    let deleted = connection
        .delete_rows(&table_name, "id", &[second_id.clone()])
        .await
        .unwrap_or_else(|error| panic!("delete_rows failed: {}", error.message));
    assert_eq!(deleted, 1, "expected one deleted row");

    let remaining_rows = fetch_rows(&connection, config.backend, &table_name, "id, name").await;
    assert_eq!(remaining_rows.len(), 1, "expected one remaining row after delete");
    assert_eq!(
        json_field_as_string(&remaining_rows[0], "id"),
        first_id,
        "delete_rows should keep the first row"
    );

    let schema_result = connection
        .apply_schema_operations(&table_name, &[build_add_status_operation()])
        .await
        .unwrap_or_else(|error| panic!("apply_schema_operations failed: {}", error.message));
    assert_schema_success(&schema_result, 1);

    let columns = connection
        .get_table_columns(&table_name)
        .await
        .unwrap_or_else(|error| panic!("get_table_columns failed: {}", error.message));
    assert!(
        columns.iter().any(|column| column.name == "status"),
        "expected added status column to exist"
    );

    let status_rows = fetch_rows(&connection, config.backend, &table_name, "id, status").await;
    assert_eq!(status_rows[0]["status"], Value::String("active".to_string()));

    drop_table_if_exists(&connection, config.backend, &table_name).await;
}

fn assert_schema_success(result: &SchemaMutationResult, expected_operations: usize) {
    assert!(result.success, "expected schema mutation success, got {:?}", result.failure);
    assert_eq!(result.total_operations, expected_operations);
    assert_eq!(result.executed_operations, expected_operations);
    assert!(!result.rolled_back, "successful schema mutation should not be rolled back");
    assert!(result.failure.is_none(), "success result should not contain failure details");
}

async fn assert_schema_failure_semantics(config: TestDbConfig, expect_rollback: bool) {
    let connection = config.connect().await;
    let table_name = unique_table_name(config.backend, "schema_failure");

    drop_table_if_exists(&connection, config.backend, &table_name).await;
    connection
        .execute_query(&config.backend.create_table_sql(&table_name))
        .await
        .unwrap_or_else(|error| panic!("Failed to create test table {}: {}", table_name, error.message));

    let result = connection
        .apply_schema_operations(
            &table_name,
            &[build_add_status_operation(), build_add_status_operation()],
        )
        .await
        .unwrap_or_else(|error| panic!("schema failure scenario failed to execute: {}", error.message));

    assert!(!result.success, "expected schema mutation to fail on duplicate add");
    assert_eq!(result.total_operations, 2);
    assert_eq!(result.executed_operations, 1);
    assert_eq!(result.rolled_back, expect_rollback);
    assert!(
        result.failure.is_some(),
        "failed schema mutation should include failure details"
    );

    let columns = connection
        .get_table_columns(&table_name)
        .await
        .unwrap_or_else(|error| panic!("get_table_columns failed: {}", error.message));
    let has_status_column = columns.iter().any(|column| column.name == "status");

    assert_eq!(
        has_status_column,
        !expect_rollback,
        "status column presence should reflect rollback semantics"
    );

    drop_table_if_exists(&connection, config.backend, &table_name).await;
}

#[tokio::test]
#[ignore = "requires BLOATSQL_TEST_POSTGRES_* env vars and a reachable PostgreSQL instance"]
async fn postgres_mutation_flow_runs_against_real_database() {
    assert_successful_mutation_flow(TestDbConfig::from_env(TestBackend::Postgres)).await;
}

#[tokio::test]
#[ignore = "requires BLOATSQL_TEST_POSTGRES_* env vars and a reachable PostgreSQL instance"]
async fn postgres_schema_failure_rolls_back_on_real_database() {
    assert_schema_failure_semantics(TestDbConfig::from_env(TestBackend::Postgres), true).await;
}

#[tokio::test]
#[ignore = "requires BLOATSQL_TEST_MARIADB_* env vars and a reachable MariaDB instance"]
async fn mariadb_mutation_flow_runs_against_real_database() {
    assert_successful_mutation_flow(TestDbConfig::from_env(TestBackend::MariaDb)).await;
}

#[tokio::test]
#[ignore = "requires BLOATSQL_TEST_MARIADB_* env vars and a reachable MariaDB instance"]
async fn mariadb_schema_failure_keeps_partial_apply_on_real_database() {
    assert_schema_failure_semantics(TestDbConfig::from_env(TestBackend::MariaDb), false).await;
}
